### ISSUE TITLE
Unable to get property 'id' of undefined or null reference

### ISSUE THREAD

**Issue by PinozenTH** [TheShadowEevee/BDSX-Discord-Chatter-Plugin#10]
D:\MCBE Server\Main\node_modules\discord.js\src\client\ClientDataManager.js:81
        guild.channels.set(channel.id, channel);
        ^
TypeError: Unable to get property 'id' of undefined or null reference
   at ClientDataManager.prototype.newChannel (D:\MCBE Server\Main\node_modules\discord.js\src\client\ClientDataManager.js:81:9)
   at Guild.prototype.setup (D:\MCBE Server\Main\node_modules\discord.js\src\structures\Guild.js:307:44)
   at GuildCreateHandler.prototype.handle (D:\MCBE Server\Main\node_modules\discord.js\src\client\websocket\packets\handlers\GuildCreate.js:12:9)
   at WebSocketPacketManager.prototype.handle (D:\MCBE Server\Main\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:34)
   at WebSocketConnection.prototype.onPacket (D:\MCBE Server\Main\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:9)
   at WebSocketConnection.prototype.onMessage (D:\MCBE Server\Main\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:299:5)
   at onMessage (D:\MCBE Server\Main\node_modules\discord.js\node_modules\ws\lib\event-target.js:120:7)
   at Reflect.apply (native code)
   at emit (events.js:189:5)
   at receiverOnMessage (D:\MCBE Server\Main\node_modules\discord.js\node_modules\ws\lib\websocket.js:789:3)
   at Reflect.apply (native code)
   at emit (events.js:189:5)
   at Receiver.prototype.dataMessage (D:\MCBE Server\Main\node_modules\discord.js\node_modules\ws\lib\receiver.js:413:9)
   at Receiver.prototype.getData (D:\MCBE Server\Main\node_modules\discord.js\node_modules\ws\lib\receiver.js:352:5)
   at Receiver.prototype.startLoop (D:\MCBE Server\Main\node_modules\discord.js\node_modules\ws\lib\receiver.js:138:11)
   at Receiver.prototype._write (D:\MCBE Server\Main\node_modules\discord.js\node_modules\ws\lib\receiver.js:74:5)

**Comment by TheShadowEevee** [comment]
Can you check a few things for me?

1. The Discord Bot you created should be in your server
2. You gave the bot a channel ID to use
3. The bot has access to the channel you provided

Thank you!

**Comment by PinozenTH** [comment]
1. Already added to the server
2. given channel ID
3. Bot had Administrator Permission ( had tested my commands with my bots before using this, Discord V13 )
Thx for the fast Replies

**Comment by TheShadowEevee** [comment]
Thanks for checking that, I'll look into this soon. While I'm not sure the exact cause I have a few things I want to try.

**Comment by PinozenTH** [comment]
Hey! Maybe Discord V11 Doesn't Support Node V16

**Comment by TheShadowEevee** [comment]
Is this still happening? Please try the latest version and if that doesn't work can you upload your config.json file? Be sure to remove your bot token but leave everything else intact.

**Comment by kaito02020424** [comment]
i know this problem.
This is an unavoidable bug due to BDSX limitations.
Specifically, Discord.js v11 doesn't support new features like stage channels.

**Comment by kaito02020424** [comment]
i know this problem.
This is an unavoidable bug due to BDSX limitations.
Specifically, Discord.js v11 doesn't support new features like stage channels.
