### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 162.159.134.233:443

### ISSUE THREAD

**Issue by bibihool** [TheShadowEevee/BDSX-Discord-Chatter-Plugin#11]
[DiscordChatter] Uncaught Error! Please report this.
(node:22756) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 162.159.134.233:443
   at afterConnect (net.js:1088:5)
(node:22756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
   at emit (events.js:180:5)
   at WebSocketConnection.prototype.onError (C:\Users\hool\Desktop\server\bdsx-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:377:5)
   at onError (C:\Users\hool\Desktop\server\bdsx-master\node_modules\ws\lib\event-target.js:128:7)
   at Reflect.apply (native code)
   at emit (events.js:189:5)
   at Anonymous function (C:\Users\hool\Desktop\server\bdsx-master\node_modules\ws\lib\websocket.js:568:5)
   at Reflect.apply (native code)
   at emit (events.js:189:5)
   at socketErrorListener (_http_client.js:399:5)
   at Reflect.apply (native code)
   at emit (events.js:189:5)
   at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
   at Reflect.apply (native code)
Exited with code 1

**Comment by TheShadowEevee** [comment]
This appears to be a network timeout; If this continues to happen check the network connection on the server.

I will implement an error check for this soon.

**Comment by TheShadowEevee** [comment]
This error check should be implemented in https://github.com/TheShadowEevee/BDSX-Discord-Chatter-Plugin/releases/tag/1.1.0.
