### ISSUE TITLE
server randomly crashes and output this

### ISSUE THREAD

**Issue by bibihool** [TheShadowEevee/BDSX-Discord-Chatter-Plugin#14]
C:\Users\hool\Desktop\server\bdsx\node_modules\sql.js\js\sql.js:5
1<process.argv.length?process.argv[1].replace(/\\/g,"/"):"unknown-program");f.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=f);process.on("uncaughtException",function(a){if(!(a instanceof ka))throw a;});f.inspect=function(){return"[Emscripten Module object]"}}else if(fa)f.print||(f.print=print),"undefined"!=typeof printErr&&(f.printErr=printErr),f.read="undefined"!=typeof read?read:function(){throw"no read() available (jsc?)";},f.readBinary=function(a){if("function"===

                                                                                                       ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
   at emit (events.js:180:5)
   at WebSocketConnection.prototype.onError (C:\Users\hool\Desktop\server\bdsx\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:377:5)
   at onError (C:\Users\hool\Desktop\server\bdsx\node_modules\discord.js\node_modules\ws\lib\event-target.js:128:7)
   at Reflect.apply (native code)
   at emit (events.js:189:5)
   at Anonymous function (C:\Users\hool\Desktop\server\bdsx\node_modules\discord.js\node_modules\ws\lib\websocket.js:568:5)
   at Reflect.apply (native code)
   at emit (events.js:189:5)
   at socketErrorListener (_http_client.js:399:5)
   at Reflect.apply (native code)
   at emit (events.js:189:5)
   at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
   at Reflect.apply (native code)
Exited with code 7

**Comment by TheShadowEevee** [comment]
I'm unable to replicate this, was this a one time thing or does it repeat? Have you changed your config at all before this started happening?

**Comment by bibihool** [comment]
it happend repeatly and this is the file https://www.mediafire.com/file/ys77wb7jolms3gs/BDSX-Discord-Chatter-Plugin-1.1.0.zip/file

**Comment by bibihool** [comment]
i think it happen more frequently when there is many people in the server

**Comment by kaito02020424** [comment]
A connection error occurs when the network connection becomes unstable or breaks for some reason.  So more people means more chances of the server crashing.  To reproduce, start the server with this plugin and disconnect from the network.  Wait a few seconds and you'll get a connection error.

**Comment by TheShadowEevee** [comment]
Sorry this took so long to fix, but as of version v1.1.4 the bot should automatically try reconnecting to Discord now.
