### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Leesw12** [TheShadowEevee/BDSX-Discord-Chatter-Plugin#17]
Error(Bugs에 제보해주세요) :  TypeError: Unable to get property 'id' of undefined or null reference
   at ClientDataManager.prototype.newChannel (C:\Users\User\Desktop\bdsx-master\node_modules\discord.js\src\client\ClientDataManager.js:81:9)
   at Guild.prototype.setup (C:\Users\User\Desktop\bdsx-master\node_modules\discord.js\src\structures\Guild.js:307:44)
   at GuildCreateHandler.prototype.handle (C:\Users\User\Desktop\bdsx-master\node_modules\discord.js\src\client\websocket\packets\handlers\GuildCreate.js:12:9)
   at WebSocketPacketManager.prototype.handle (C:\Users\User\Desktop\bdsx-master\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:34)
   at WebSocketConnection.prototype.onPacket (C:\Users\User\Desktop\bdsx-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:9)
   at WebSocketConnection.prototype.onMessage (C:\Users\User\Desktop\bdsx-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:299:5)
   at onMessage (C:\Users\User\Desktop\bdsx-master\node_modules\ws\lib\event-target.js:120:7)
   at Reflect.apply (native code)
   at emit (events.js:189:5)
   at receiverOnMessage (C:\Users\User\Desktop\bdsx-master\node_modules\ws\lib\websocket.js:789:3)
   at Reflect.apply (native code)
   at emit (events.js:189:5)
   at Receiver.prototype.dataMessage (C:\Users\User\Desktop\bdsx-master\node_modules\ws\lib\receiver.js:413:9)
   at Receiver.prototype.getData (C:\Users\User\Desktop\bdsx-master\node_modules\ws\lib\receiver.js:352:5)
   at Receiver.prototype.startLoop (C:\Users\User\Desktop\bdsx-master\node_modules\ws\lib\receiver.js:138:11)
   at Receiver.prototype._write (C:\Users\User\Desktop\bdsx-master\node_modules\ws\lib\receiver.js:74:5)
please fix the bug

**Comment by kaito02020424** [comment]
i know this problem.
This is an unavoidable bug due to BDSX limitations.
Specifically, Discord.js v11 doesn't support new features like stage channels.

**Comment by leesw164** [comment]
okay

**Comment by TheShadowEevee** [comment]
I'm closing this as a known issue that I don't have control over. At least in the current version, the bot still seems to operate; it just puts out an error while doing so. Everything else still should work.
