### ISSUE TITLE
Plugin Initializes chat bridge before server is running, crashing the server if a Discord message is sent during the launch window

### ISSUE THREAD

**Issue by bibihool** [TheShadowEevee/BDSX-Discord-Chatter-Plugin#6]
![image](https://user-images.githubusercontent.com/72029878/140318713-a6c3f0b0-f175-4eae-8053-d35cafb925b7.png)

**Comment by TheShadowEevee** [comment]
Can you post your full terminal output including the command you ran all the way till the program exits

**Comment by bibihool** [comment]
you mean this?

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
   at emit (events.js:180:5)
   at WebSocketConnection.prototype.onError (C:\Users\hool\Desktop\New folder\bdsx\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:377:5)
   at onError (C:\Users\hool\Desktop\New folder\bdsx\node_modules\ws\lib\event-target.js:128:7)
   at Reflect.apply (native code)
   at emit (events.js:189:5)
   at Anonymous function (C:\Users\hool\Desktop\New folder\bdsx\node_modules\ws\lib\websocket.js:568:5)
   at Reflect.apply (native code)
   at emit (events.js:189:5)
   at socketErrorListener (_http_client.js:399:5)
   at Reflect.apply (native code)
   at emit (events.js:189:5)
   at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
   at Reflect.apply (native code)
Exited with code 1
Re-Launch BDSX
3
2
1
  _____      _____
  \    \    /    /
   \___ \__/ ___/
   | _ )   \/ __|
   | _ \ |) \__ \
   |___/___/|___/
   /    /  \    \
  /____/    \____\

[BDSX] Generated Machine Code: 48 bytes
[BDSX-Plugins] Loading @bdsx/BDSX-Discord-Chatter-Plugin-1.0.3 (1/4)
[DiscordChatter] Starting DiscordChatter!
[DiscordChatter] DiscordChatter is version 1.0.2.
[BDSX-Plugins] Loading @bdsx/aniketos (2/4)
      ___           ___                       ___           ___                       ___           ___
     /  /\         /__/\        ___          /__/|         /  /\          ___        /  /\         /  /\
    /  /::\        \  \:\      /  /\        |  |:|        /  /:/_        /  /\      /  /::\       /  /:/_
   /  /:/\:\        \  \:\    /  /:/        |  |:|       /  /:/ /\      /  /:/     /  /:/\:\     /  /:/ /\
  /  /:/~/::\   _____\__\:\  /__/::\      __|  |:|      /  /:/ /:/_    /  /:/     /  /:/  \:\   /  /:/ /::\
 /__/:/ /:/\:\ /__/::::::::\ \__\/\:\__  /__/\_|:|____ /__/:/ /:/ /\  /  /::\    /__/:/ \__\:\ /__/:/ /:/\:\
 \  \:\/:/__\/ \  \:\~~\~~\/    \  \:\/\ \  \:\/:::::/ \  \:\/:/ /:/ /__/:/\:\   \  \:\ /  /:/ \  \:\/:/~/:/
  \  \::/       \  \:\  ~~~      \__\::/  \  \::/~~~~   \  \::/ /:/  \__\/  \:\   \  \:\  /:/   \  \::/ /:/
   \  \:\        \  \:\          /__/:/    \  \:\        \  \:\/:/        \  \:\   \  \:\/:/     \__\/ /:/
    \  \:\        \  \:\         \__\/      \  \:\        \  \::/          \__\/    \  \::/        /__/:/
     \__\/         \__\/                     \__\/         \__\/                     \__\/         \__\/
[BDSX-Plugins] Loading @bdsx/image-maps (3/4)
[BDSX-Plugins] Loading @bdsx/ping (4/4)
[BDSX] bedrockServer is launching...
[BDSX] Generated Machine Code: 100 bytes
NO LOG FILE! - [] setting up server logging...
[2021-11-04 20:53:10:237 INFO] Starting Server
[2021-11-04 20:53:10:238 INFO] Version 1.17.41.01
[2021-11-04 20:53:10:238 INFO] Session ID fa979aec-8807-46d6-bf35-8801c2053674
[2021-11-04 20:53:10:238 INFO] Level Name: newsurvival4
[2021-11-04 20:53:10:247 INFO] Game mode: 0 Survival
[2021-11-04 20:53:10:247 INFO] Difficulty: 3 HARD
[INFO] opening worlds/newsurvival4/db
[DiscordChatter] Logged in as In game#2283!
[DiscordChatter] DiscordChatter has started.

C:\Users\hool\Desktop\New folder\bdsx\bdsx\launcher.ts:389
        const origin = createServerCommandOrigin('Server',
        ^
Error: bedrock_server is not launched yet
   at executeCommand (C:\Users\hool\Desktop\New folder\bdsx\bdsx\launcher.ts:389:9)
   at SendToGame (C:\Users\hool\Desktop\New folder\bdsx\plugins\BDSX-Discord-Chatter-Plugin-1.0.3\index.ts:203:5)
   at Anonymous function (C:\Users\hool\Desktop\New folder\bdsx\plugins\BDSX-Discord-Chatter-Plugin-1.0.3\index.ts:89:9)   at Reflect.apply (native code)
   at emit (events.js:189:5)
   at MessageCreateHandler.prototype.handle (C:\Users\hool\Desktop\New folder\bdsx\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:27)
   at WebSocketPacketManager.prototype.handle (C:\Users\hool\Desktop\New folder\bdsx\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:34)
   at WebSocketConnection.prototype.onPacket (C:\Users\hool\Desktop\New folder\bdsx\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:9)
   at WebSocketConnection.prototype.onMessage (C:\Users\hool\Desktop\New folder\bdsx\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:299:5)
   at onMessage (C:\Users\hool\Desktop\New folder\bdsx\node_modules\ws\lib\event-target.js:120:7)
   at Reflect.apply (native code)
   at emit (events.js:189:5)
   at receiverOnMessage (C:\Users\hool\Desktop\New folder\bdsx\node_modules\ws\lib\websocket.js:789:3)
   at Reflect.apply (native code)
   at emit (events.js:189:5)
Exited with code 1
Re-Launch BDSX
3
2
1
  _____      _____
  \    \    /    /
   \___ \__/ ___/
   | _ )   \/ __|
   | _ \ |) \__ \
   |___/___/|___/
   /    /  \    \
  /____/    \____\

[BDSX] Generated Machine Code: 48 bytes
[BDSX-Plugins] Loading @bdsx/BDSX-Discord-Chatter-Plugin-1.0.3 (1/4)
[DiscordChatter] Starting DiscordChatter!
[DiscordChatter] DiscordChatter is version 1.0.2.
[BDSX-Plugins] Loading @bdsx/aniketos (2/4)
      ___           ___                       ___           ___                       ___           ___
     /  /\         /__/\        ___          /__/|         /  /\          ___        /  /\         /  /\
    /  /::\        \  \:\      /  /\        |  |:|        /  /:/_        /  /\      /  /::\       /  /:/_
   /  /:/\:\        \  \:\    /  /:/        |  |:|       /  /:/ /\      /  /:/     /  /:/\:\     /  /:/ /\
  /  /:/~/::\   _____\__\:\  /__/::\      __|  |:|      /  /:/ /:/_    /  /:/     /  /:/  \:\   /  /:/ /::\
 /__/:/ /:/\:\ /__/::::::::\ \__\/\:\__  /__/\_|:|____ /__/:/ /:/ /\  /  /::\    /__/:/ \__\:\ /__/:/ /:/\:\
 \  \:\/:/__\/ \  \:\~~\~~\/    \  \:\/\ \  \:\/:::::/ \  \:\/:/ /:/ /__/:/\:\   \  \:\ /  /:/ \  \:\/:/~/:/
  \  \::/       \  \:\  ~~~      \__\::/  \  \::/~~~~   \  \::/ /:/  \__\/  \:\   \  \:\  /:/   \  \::/ /:/
   \  \:\        \  \:\          /__/:/    \  \:\        \  \:\/:/        \  \:\   \  \:\/:/     \__\/ /:/
    \  \:\        \  \:\         \__\/      \  \:\        \  \::/          \__\/    \  \::/        /__/:/
     \__\/         \__\/                     \__\/         \__\/                     \__\/         \__\/
[BDSX-Plugins] Loading @bdsx/image-maps (3/4)
[BDSX-Plugins] Loading @bdsx/ping (4/4)
[BDSX] bedrockServer is launching...
[BDSX] Generated Machine Code: 100 bytes
NO LOG FILE! - [] setting up server logging...
[2021-11-04 20:53:23:962 INFO] Starting Server
[2021-11-04 20:53:23:962 INFO] Version 1.17.41.01
[2021-11-04 20:53:23:962 INFO] Session ID 9eb54482-598f-4d82-958b-07c40744688f
[2021-11-04 20:53:23:963 INFO] Level Name: newsurvival4
[2021-11-04 20:53:23:964 INFO] Game mode: 0 Survival
[2021-11-04 20:53:23:964 INFO] Difficulty: 3 HARD
[INFO] opening worlds/newsurvival4/db
[DiscordChatter] Logged in as In game#2283!
[DiscordChatter] DiscordChatter has started.

C:\Users\hool\Desktop\New folder\bdsx\bdsx\launcher.ts:389
        const origin = createServerCommandOrigin('Server',
        ^
Error: bedrock_server is not launched yet
   at executeCommand (C:\Users\hool\Desktop\New folder\bdsx\bdsx\launcher.ts:389:9)
   at SendToGame (C:\Users\hool\Desktop\New folder\bdsx\plugins\BDSX-Discord-Chatter-Plugin-1.0.3\index.ts:203:5)
   at Anonymous function (C:\Users\hool\Desktop\New folder\bdsx\plugins\BDSX-Discord-Chatter-Plugin-1.0.3\index.ts:89:9)   at Reflect.apply (native code)
   at emit (events.js:189:5)
   at MessageCreateHandler.prototype.handle (C:\Users\hool\Desktop\New folder\bdsx\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:27)
   at WebSocketPacketManager.prototype.handle (C:\Users\hool\Desktop\New folder\bdsx\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:34)
   at WebSocketConnection.prototype.onPacket (C:\Users\hool\Desktop\New folder\bdsx\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:9)
   at WebSocketConnection.prototype.onMessage (C:\Users\hool\Desktop\New folder\bdsx\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:299:5)
   at onMessage (C:\Users\hool\Desktop\New folder\bdsx\node_modules\ws\lib\event-target.js:120:7)
   at Reflect.apply (native code)
   at emit (events.js:189:5)
   at receiverOnMessage (C:\Users\hool\Desktop\New folder\bdsx\node_modules\ws\lib\websocket.js:789:3)
   at Reflect.apply (native code)
   at emit (events.js:189:5)
Exited with code 1
Re-Launch BDSX
3
2
1
  _____      _____
  \    \    /    /
   \___ \__/ ___/
   | _ )   \/ __|
   | _ \ |) \__ \
   |___/___/|___/
   /    /  \    \
  /____/    \____\

[BDSX] Generated Machine Code: 48 bytes
[BDSX-Plugins] Loading @bdsx/BDSX-Discord-Chatter-Plugin-1.0.3 (1/4)
[DiscordChatter] Starting DiscordChatter!
[DiscordChatter] DiscordChatter is version 1.0.2.
[BDSX-Plugins] Loading @bdsx/aniketos (2/4)
      ___           ___                       ___           ___                       ___           ___
     /  /\         /__/\        ___          /__/|         /  /\          ___        /  /\         /  /\
    /  /::\        \  \:\      /  /\        |  |:|        /  /:/_        /  /\      /  /::\       /  /:/_
   /  /:/\:\        \  \:\    /  /:/        |  |:|       /  /:/ /\      /  /:/     /  /:/\:\     /  /:/ /\
  /  /:/~/::\   _____\__\:\  /__/::\      __|  |:|      /  /:/ /:/_    /  /:/     /  /:/  \:\   /  /:/ /::\
 /__/:/ /:/\:\ /__/::::::::\ \__\/\:\__  /__/\_|:|____ /__/:/ /:/ /\  /  /::\    /__/:/ \__\:\ /__/:/ /:/\:\
 \  \:\/:/__\/ \  \:\~~\~~\/    \  \:\/\ \  \:\/:::::/ \  \:\/:/ /:/ /__/:/\:\   \  \:\ /  /:/ \  \:\/:/~/:/
  \  \::/       \  \:\  ~~~      \__\::/  \  \::/~~~~   \  \::/ /:/  \__\/  \:\   \  \:\  /:/   \  \::/ /:/
   \  \:\        \  \:\          /__/:/    \  \:\        \  \:\/:/        \  \:\   \  \:\/:/     \__\/ /:/
    \  \:\        \  \:\         \__\/      \  \:\        \  \::/          \__\/    \  \::/        /__/:/
     \__\/         \__\/                     \__\/         \__\/                     \__\/         \__\/
[BDSX-Plugins] Loading @bdsx/image-maps (3/4)
[BDSX-Plugins] Loading @bdsx/ping (4/4)
[BDSX] bedrockServer is launching...
[BDSX] Generated Machine Code: 100 bytes
NO LOG FILE! - [] setting up server logging...
[2021-11-04 20:53:33:548 INFO] Starting Server
[2021-11-04 20:53:33:548 INFO] Version 1.17.41.01
[2021-11-04 20:53:33:548 INFO] Session ID 892a33ab-15b5-43a4-97a7-1dd732a9ae29
[2021-11-04 20:53:33:548 INFO] Level Name: newsurvival4
[2021-11-04 20:53:33:550 INFO] Game mode: 0 Survival
[2021-11-04 20:53:33:550 INFO] Difficulty: 3 HARD
[INFO] opening worlds/newsurvival4/db
[DiscordChatter] Logged in as In game#2283!
[DiscordChatter] DiscordChatter has started.
[INFO] IPv4 supported, port: 19132
[INFO] IPv6 supported, port: 19133
[INFO] Server started.
stopststostostoHi,this is bibihool's plugins
logTexts is loaded
bowDing.ts loaded
[BDSX] Generated Machine Code: 48 bytes
[INFO] IPv4 supported, port: 50781
[INFO] IPv6 supported, port: 50782

**Comment by TheShadowEevee** [comment]
Is the discord server fairly active? It's possible that a message is coming through while the mc server is still booting. There should be a check for this in place, I will look into it soon.

**Comment by bibihool** [comment]
i dont quite understand what you mean message is coming through while the mc server is still booting.I was just playing with my freinds normally and this happens.I assumed it happens when someone join and leave the server?

**Comment by TheShadowEevee** [comment]
While testing #8 I have confirmed the issue causing this to happen.

As soon as I can find a way to listen for BDS to finish initializing, or simply wrap the block in an error catch, I'll commit a fix.

**Comment by TheShadowEevee** [comment]
This should be fixed in Hotfix v1.0.5.

Please download the patch [here](https://github.com/TheShadowEevee/BDSX-Discord-Chatter-Plugin/releases/tag/1.0.5).
